// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "imdb-charts": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-charts",
    "method": "GET",
    "path": "/imdb/charts",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "top_rated_movies",
          "top_rated_tv_shows",
          "most_popular_movies",
          "most_popular_tv_shows",
          "top_rated_english_movies",
          "lowest_rated_movies"
        ],
        "in": "query",
        "name": "chart",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-image-types": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-image-types",
    "method": "GET",
    "path": "/imdb/image-types",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-name": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-name",
    "method": "GET",
    "path": "/imdb/name",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-name-awards": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-name-awards",
    "method": "GET",
    "path": "/imdb/name/awards",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-name-credits": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-name-credits",
    "method": "GET",
    "path": "/imdb/name/credits",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-name-images": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-name-images",
    "method": "GET",
    "path": "/imdb/name/images",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      },
      {
        "enum": [
          "behind_the_scenes",
          "event",
          "poster",
          "product",
          "production_art",
          "publicity",
          "still_frame",
          "unknown"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-name-videos": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-name-videos",
    "method": "GET",
    "path": "/imdb/name/videos",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-search",
    "method": "GET",
    "path": "/imdb/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "query",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-search-title": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-search-title",
    "method": "GET",
    "path": "/imdb/search/title",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "title",
        "type": "string"
      },
      {
        "in": "query",
        "name": "title_type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "genres",
        "type": "string"
      },
      {
        "in": "query",
        "name": "release_date_from",
        "type": "string"
      },
      {
        "in": "query",
        "name": "release_date_to",
        "type": "string"
      },
      {
        "in": "query",
        "name": "min_user_rating",
        "type": "number"
      },
      {
        "in": "query",
        "name": "max_user_rating",
        "type": "number"
      },
      {
        "in": "query",
        "name": "min_votes",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "max_votes",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "min_popularity",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "max_popularity",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "min_runtime",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "max_runtime",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "groups",
        "type": "string"
      },
      {
        "in": "query",
        "name": "keywords",
        "type": "string"
      },
      {
        "in": "query",
        "name": "companies",
        "type": "string"
      },
      {
        "in": "query",
        "name": "certificates",
        "type": "string"
      },
      {
        "in": "query",
        "name": "colors",
        "type": "string"
      },
      {
        "in": "query",
        "name": "countries",
        "type": "string"
      },
      {
        "in": "query",
        "name": "languages",
        "type": "string"
      },
      {
        "in": "query",
        "name": "sound_mixes",
        "type": "string"
      },
      {
        "in": "query",
        "name": "role",
        "type": "string"
      },
      {
        "in": "query",
        "name": "characters",
        "type": "string"
      },
      {
        "in": "query",
        "name": "plot",
        "type": "string"
      },
      {
        "in": "query",
        "name": "include_adult",
        "type": "boolean"
      },
      {
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "in": "query",
        "name": "sort_order",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title",
    "method": "GET",
    "path": "/imdb/title",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-awards": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-awards",
    "method": "GET",
    "path": "/imdb/title/awards",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-box-office": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-box-office",
    "method": "GET",
    "path": "/imdb/title/box-office",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-company-credits": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-company-credits",
    "method": "GET",
    "path": "/imdb/title/company-credits",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-connections": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-connections",
    "method": "GET",
    "path": "/imdb/title/connections",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-credits": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-credits",
    "method": "GET",
    "path": "/imdb/title/credits",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-episodes": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-episodes",
    "method": "GET",
    "path": "/imdb/title/episodes",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-filming-locations": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-filming-locations",
    "method": "GET",
    "path": "/imdb/title/filming-locations",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-goofs": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-goofs",
    "method": "GET",
    "path": "/imdb/title/goofs",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-images": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-images",
    "method": "GET",
    "path": "/imdb/title/images",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      },
      {
        "enum": [
          "behind_the_scenes",
          "event",
          "poster",
          "product",
          "production_art",
          "publicity",
          "still_frame",
          "unknown"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-keywords": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-keywords",
    "method": "GET",
    "path": "/imdb/title/keywords",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-parental-guide": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-parental-guide",
    "method": "GET",
    "path": "/imdb/title/parental-guide",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-public-facts-analysis": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-public-facts-analysis",
    "method": "GET",
    "path": "/imdb/title/public-facts-analysis",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-quotes": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-quotes",
    "method": "GET",
    "path": "/imdb/title/quotes",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-ratings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-ratings",
    "method": "GET",
    "path": "/imdb/title/ratings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-release-info": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-release-info",
    "method": "GET",
    "path": "/imdb/title/release-info",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-reviews": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-reviews",
    "method": "GET",
    "path": "/imdb/title/reviews",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-similar": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-similar",
    "method": "GET",
    "path": "/imdb/title/similar",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-technical-specs": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-technical-specs",
    "method": "GET",
    "path": "/imdb/title/technical-specs",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-trivia": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-trivia",
    "method": "GET",
    "path": "/imdb/title/trivia",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "imdb-title-videos": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "imdb-title-videos",
    "method": "GET",
    "path": "/imdb/title/videos",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "url",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "imdb": {
    "charts": "imdb-charts",
    "imageTypes": "imdb-image-types",
    "name": "imdb-name",
    "nameAwards": "imdb-name-awards",
    "nameCredits": "imdb-name-credits",
    "nameImages": "imdb-name-images",
    "nameVideos": "imdb-name-videos",
    "search": "imdb-search",
    "searchTitle": "imdb-search-title",
    "title": "imdb-title",
    "titleAwards": "imdb-title-awards",
    "titleBoxOffice": "imdb-title-box-office",
    "titleCompanyCredits": "imdb-title-company-credits",
    "titleConnections": "imdb-title-connections",
    "titleCredits": "imdb-title-credits",
    "titleEpisodes": "imdb-title-episodes",
    "titleFilmingLocations": "imdb-title-filming-locations",
    "titleGoofs": "imdb-title-goofs",
    "titleImages": "imdb-title-images",
    "titleKeywords": "imdb-title-keywords",
    "titleParentalGuide": "imdb-title-parental-guide",
    "titlePublicFactsAnalysis": "imdb-title-public-facts-analysis",
    "titleQuotes": "imdb-title-quotes",
    "titleRatings": "imdb-title-ratings",
    "titleReleaseInfo": "imdb-title-release-info",
    "titleReviews": "imdb-title-reviews",
    "titleSimilar": "imdb-title-similar",
    "titleTechnicalSpecs": "imdb-title-technical-specs",
    "titleTrivia": "imdb-title-trivia",
    "titleVideos": "imdb-title-videos"
  }
};

export const operationCount = 30;

export const OperationIds = Object.freeze({
  "ImdbCharts": "imdb-charts",
  "ImdbImageTypes": "imdb-image-types",
  "ImdbName": "imdb-name",
  "ImdbNameAwards": "imdb-name-awards",
  "ImdbNameCredits": "imdb-name-credits",
  "ImdbNameImages": "imdb-name-images",
  "ImdbNameVideos": "imdb-name-videos",
  "ImdbSearch": "imdb-search",
  "ImdbSearchTitle": "imdb-search-title",
  "ImdbTitle": "imdb-title",
  "ImdbTitleAwards": "imdb-title-awards",
  "ImdbTitleBoxOffice": "imdb-title-box-office",
  "ImdbTitleCompanyCredits": "imdb-title-company-credits",
  "ImdbTitleConnections": "imdb-title-connections",
  "ImdbTitleCredits": "imdb-title-credits",
  "ImdbTitleEpisodes": "imdb-title-episodes",
  "ImdbTitleFilmingLocations": "imdb-title-filming-locations",
  "ImdbTitleGoofs": "imdb-title-goofs",
  "ImdbTitleImages": "imdb-title-images",
  "ImdbTitleKeywords": "imdb-title-keywords",
  "ImdbTitleParentalGuide": "imdb-title-parental-guide",
  "ImdbTitlePublicFactsAnalysis": "imdb-title-public-facts-analysis",
  "ImdbTitleQuotes": "imdb-title-quotes",
  "ImdbTitleRatings": "imdb-title-ratings",
  "ImdbTitleReleaseInfo": "imdb-title-release-info",
  "ImdbTitleReviews": "imdb-title-reviews",
  "ImdbTitleSimilar": "imdb-title-similar",
  "ImdbTitleTechnicalSpecs": "imdb-title-technical-specs",
  "ImdbTitleTrivia": "imdb-title-trivia",
  "ImdbTitleVideos": "imdb-title-videos"
});
