// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelImdbTitleVideosResponseDoc {
  "code"?: number;
  "data"?: ModelImdbTitleVideosResponse;
  "msg"?: string;
}

export interface ModelImdbTitleVideosResponse {
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "limit"?: number;
  "source_url"?: string;
  "title"?: string;
  "total"?: number;
  "url"?: string;
  "videos"?: Array<ModelImdbVideoItem>;
}

export interface ModelImdbVideoItem {
  "content_type"?: string;
  "duration_seconds"?: number;
  "id"?: string;
  "position"?: number;
  "primary_title"?: ModelImdbVideoPrimaryTitle;
  "thumbnail"?: ModelImdbVideoThumbnail;
  "title"?: string;
}

export interface ModelImdbVideoThumbnail {
  "height"?: number;
  "url"?: string;
  "width"?: number;
}

export interface ModelImdbVideoPrimaryTitle {
  "id"?: string;
  "title"?: string;
  "url"?: string;
}

export interface ModelImdbTitlePublicFactsResponseDoc {
  "code"?: number;
  "data"?: ModelImdbTitlePublicFactsResponse;
  "msg"?: string;
}

export interface ModelImdbTitlePublicFactsResponse {
  "company_credits"?: Array<ModelImdbCompanySection>;
  "facts"?: Array<ModelImdbPublicFactItem>;
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "keywords"?: Array<ModelImdbKeywordItem>;
  "locations"?: Array<ModelImdbLocationItem>;
  "public_page_derived"?: boolean;
  "source_url"?: string;
  "total"?: number;
  "type"?: string;
  "url"?: string;
}

export interface ModelImdbLocationItem {
  "location"?: string;
  "note"?: string;
  "public_signals"?: number;
}

export interface ModelImdbKeywordItem {
  "keyword"?: string;
  "public_signals"?: number;
  "url"?: string;
}

export interface ModelImdbPublicFactItem {
  "category"?: string;
  "public_signals"?: number;
  "spoiler"?: boolean;
  "text"?: string;
}

export interface ModelImdbCompanySection {
  "companies"?: Array<ModelImdbCompanyItem>;
  "name"?: string;
  "slug"?: string;
}

export interface ModelImdbCompanyItem {
  "name"?: string;
  "note"?: string;
  "public_signals"?: number;
  "url"?: string;
}

export interface ModelImdbTechnicalSpecsResponseDoc {
  "code"?: number;
  "data"?: ModelImdbTechnicalSpecsResponse;
  "msg"?: string;
}

export interface ModelImdbTechnicalSpecsResponse {
  "fetched_at"?: string;
  "id"?: string;
  "public_page_derived"?: boolean;
  "source_url"?: string;
  "specs"?: Array<ModelImdbTechnicalSpecItem>;
  "url"?: string;
}

export interface ModelImdbTechnicalSpecItem {
  "name"?: string;
  "slug"?: string;
  "values"?: Array<string>;
}

export interface ModelImdbSimilarResponseDoc {
  "code"?: number;
  "data"?: ModelImdbSimilarResponse;
  "msg"?: string;
}

export interface ModelImdbSimilarResponse {
  "fetched_at"?: string;
  "id"?: string;
  "source_url"?: string;
  "titles"?: Array<ModelImdbSimilarTitle>;
  "url"?: string;
}

export interface ModelImdbSimilarTitle {
  "content_rating"?: string;
  "id"?: string;
  "image_url"?: string;
  "rating_count"?: number;
  "rating_value"?: number;
  "runtime_minutes"?: number;
  "title"?: string;
  "title_type"?: string;
  "url"?: string;
  "year"?: number;
}

export interface ModelImdbReviewsResponseDoc {
  "code"?: number;
  "data"?: ModelImdbReviewsResponse;
  "msg"?: string;
}

export interface ModelImdbReviewsResponse {
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "limit"?: number;
  "public_page_derived"?: boolean;
  "reviews"?: Array<ModelImdbReviewItem>;
  "source_url"?: string;
  "total"?: number;
  "url"?: string;
}

export interface ModelImdbReviewItem {
  "author"?: string;
  "date"?: string;
  "helpful_votes"?: number;
  "helpfulness"?: string;
  "id"?: string;
  "public_signals"?: number;
  "rating"?: number;
  "spoiler"?: boolean;
  "text"?: string;
  "title"?: string;
  "total_votes"?: number;
  "url"?: string;
}

export interface ModelImdbReleaseInfoResponseDoc {
  "code"?: number;
  "data"?: ModelImdbReleaseInfoResponse;
  "msg"?: string;
}

export interface ModelImdbReleaseInfoResponse {
  "alternate_titles"?: Array<ModelImdbAlternateTitle>;
  "alternate_titles_total"?: number;
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "public_page_derived"?: boolean;
  "releases"?: Array<ModelImdbReleaseInfoItem>;
  "source_url"?: string;
  "total"?: number;
  "url"?: string;
}

export interface ModelImdbReleaseInfoItem {
  "country"?: string;
  "date"?: string;
  "note"?: string;
}

export interface ModelImdbAlternateTitle {
  "country"?: string;
  "title"?: string;
  "type"?: string;
}

export interface ModelImdbRatingsResponseDoc {
  "code"?: number;
  "data"?: ModelImdbRatingsResponse;
  "msg"?: string;
}

export interface ModelImdbRatingsResponse {
  "countries"?: Array<ModelImdbRatingCountrySummary>;
  "fetched_at"?: string;
  "histogram"?: Array<ModelImdbRatingHistogramBucket>;
  "id"?: string;
  "rating_count"?: number;
  "rating_value"?: number;
  "source_url"?: string;
  "title"?: string;
  "url"?: string;
}

export interface ModelImdbRatingHistogramBucket {
  "rating"?: number;
  "vote_count"?: number;
}

export interface ModelImdbRatingCountrySummary {
  "aggregate"?: number;
  "country"?: string;
  "vote_count"?: number;
}

export interface ModelImdbTitlePublicFactsAnalysisResponseDoc {
  "code"?: number;
  "data"?: ModelImdbTitlePublicFactsAnalysisResponse;
  "msg"?: string;
}

export interface ModelImdbTitlePublicFactsAnalysisResponse {
  "company_credits"?: ModelImdbTitlePublicFactsResponse;
  "filming_locations"?: ModelImdbTitlePublicFactsResponse;
  "goofs"?: ModelImdbTitlePublicFactsResponse;
  "keywords"?: ModelImdbTitlePublicFactsResponse;
  "missing_sections"?: Array<string>;
  "not_viewing_advice"?: boolean;
  "partial"?: boolean;
  "public_page_derived"?: boolean;
  "quotes"?: ModelImdbTitlePublicFactsResponse;
  "summary"?: ModelImdbPublicFactsAnalysisSummary;
  "trivia"?: ModelImdbTitlePublicFactsResponse;
}

export interface ModelImdbPublicFactsAnalysisSummary {
  "company_count"?: number;
  "company_section_count"?: number;
  "filming_location_count"?: number;
  "goof_count"?: number;
  "keyword_count"?: number;
  "public_fact_coverage_pages"?: number;
  "public_page_signals"?: number;
  "quote_count"?: number;
  "spoiler_fact_count"?: number;
  "trivia_count"?: number;
}

export interface ModelImdbParentalGuideResponseDoc {
  "code"?: number;
  "data"?: ModelImdbParentalGuideResponse;
  "msg"?: string;
}

export interface ModelImdbParentalGuideResponse {
  "categories"?: Array<ModelImdbParentalGuideCategory>;
  "fetched_at"?: string;
  "id"?: string;
  "public_page_derived"?: boolean;
  "source_url"?: string;
  "summary"?: ModelImdbParentalGuideSummary;
  "url"?: string;
}

export interface ModelImdbParentalGuideSummary {
  "categories_count"?: number;
  "highest_severity"?: string;
  "item_count"?: number;
  "present_categories"?: Array<string>;
  "public_page_signals"?: number;
  "severity_counts"?: Record<string, number>;
}

export interface ModelImdbParentalGuideCategory {
  "items"?: Array<string>;
  "name"?: string;
  "severity"?: string;
  "slug"?: string;
}

export interface ModelImdbTitleImagesResponseDoc {
  "code"?: number;
  "data"?: ModelImdbTitleImagesResponse;
  "msg"?: string;
}

export interface ModelImdbTitleImagesResponse {
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "images"?: Array<ModelImdbImageItem>;
  "limit"?: number;
  "source_url"?: string;
  "title"?: string;
  "total"?: number;
  "type_counts"?: Array<ModelImdbImageTypeCount>;
  "types"?: Array<string>;
  "url"?: string;
}

export interface ModelImdbImageTypeCount {
  "label"?: string;
  "total"?: number;
  "type"?: string;
}

export interface ModelImdbImageItem {
  "caption"?: string;
  "copyright"?: string;
  "countries"?: Array<ModelImdbImageLocale>;
  "created_by"?: string;
  "created_on"?: string;
  "height"?: number;
  "id"?: string;
  "languages"?: Array<ModelImdbImageLocale>;
  "names"?: Array<ModelImdbImageName>;
  "position"?: number;
  "source"?: string;
  "titles"?: Array<ModelImdbImageTitle>;
  "type"?: string;
  "url"?: string;
  "width"?: number;
}

export interface ModelImdbImageTitle {
  "id"?: string;
  "title"?: string;
  "url"?: string;
  "year"?: number;
}

export interface ModelImdbImageName {
  "id"?: string;
  "name"?: string;
  "url"?: string;
}

export interface ModelImdbImageLocale {
  "code"?: string;
  "name"?: string;
}

export interface ModelImdbEpisodesResponseDoc {
  "code"?: number;
  "data"?: ModelImdbEpisodesResponse;
  "msg"?: string;
}

export interface ModelImdbEpisodesResponse {
  "episodes"?: Array<ModelImdbEpisodeItem>;
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "limit"?: number;
  "public_page_derived"?: boolean;
  "season"?: number;
  "source_url"?: string;
  "total"?: number;
  "url"?: string;
}

export interface ModelImdbEpisodeItem {
  "air_date"?: string;
  "episode"?: number;
  "id"?: string;
  "plot"?: string;
  "public_signals"?: number;
  "rating_count"?: number;
  "rating_value"?: number;
  "season"?: number;
  "title"?: string;
  "url"?: string;
}

export interface ModelImdbCreditsResponseDoc {
  "code"?: number;
  "data"?: ModelImdbCreditsResponse;
  "msg"?: string;
}

export interface ModelImdbCreditsResponse {
  "fetched_at"?: string;
  "id"?: string;
  "public_page_derived"?: boolean;
  "sections"?: Array<ModelImdbCreditSection>;
  "source_url"?: string;
  "url"?: string;
}

export interface ModelImdbCreditSection {
  "credits"?: Array<ModelImdbCreditItem>;
  "has_more"?: boolean;
  "name"?: string;
  "slug"?: string;
  "total"?: number;
}

export interface ModelImdbCreditItem {
  "character"?: string;
  "name"?: string;
  "role"?: string;
  "url"?: string;
}

export interface ModelImdbTitleConnectionsResponseDoc {
  "code"?: number;
  "data"?: ModelImdbTitleConnectionsResponse;
  "msg"?: string;
}

export interface ModelImdbTitleConnectionsResponse {
  "connections"?: Array<ModelImdbConnectionItem>;
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "limit"?: number;
  "source_url"?: string;
  "title"?: string;
  "total"?: number;
  "url"?: string;
}

export interface ModelImdbConnectionItem {
  "associated_title"?: ModelImdbConnectionAssociatedTitle;
  "category"?: string;
  "note"?: string;
}

export interface ModelImdbConnectionAssociatedTitle {
  "id"?: string;
  "title"?: string;
  "title_type"?: string;
  "url"?: string;
  "year"?: number;
}

export interface ModelImdbTitleBoxOfficeResponseDoc {
  "code"?: number;
  "data"?: ModelImdbTitleBoxOfficeResponse;
  "msg"?: string;
}

export interface ModelImdbTitleBoxOfficeResponse {
  "fetched_at"?: string;
  "has_box_office"?: boolean;
  "id"?: string;
  "lifetime_gross"?: ModelImdbLifetimeGross;
  "opening_weekend"?: ModelImdbOpeningWeekend;
  "production_budget"?: ModelImdbMoney;
  "source_url"?: string;
  "title"?: string;
  "url"?: string;
}

export interface ModelImdbMoney {
  "amount"?: number;
  "currency"?: string;
}

export interface ModelImdbOpeningWeekend {
  "gross"?: ModelImdbMoney;
  "theater_count"?: number;
  "weekend_end_date"?: string;
  "weekend_start_date"?: string;
}

export interface ModelImdbLifetimeGross {
  "domestic"?: ModelImdbMoney;
  "international"?: ModelImdbMoney;
  "worldwide"?: ModelImdbMoney;
}

export interface ModelImdbTitleAwardsResponseDoc {
  "code"?: number;
  "data"?: ModelImdbTitleAwardsResponse;
  "msg"?: string;
}

export interface ModelImdbTitleAwardsResponse {
  "awards"?: Array<ModelImdbAwardItem>;
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "public_page_derived"?: boolean;
  "source_url"?: string;
  "total"?: number;
  "url"?: string;
}

export interface ModelImdbAwardItem {
  "award"?: string;
  "category"?: string;
  "event"?: string;
  "notes"?: string;
  "public_signals"?: number;
  "recipients"?: Array<ModelImdbPerson>;
  "result"?: string;
  "titles"?: Array<ModelImdbAwardTitle>;
  "year"?: string;
}

export interface ModelImdbAwardTitle {
  "id"?: string;
  "title"?: string;
  "url"?: string;
}

export interface ModelImdbPerson {
  "name"?: string;
  "url"?: string;
}

export interface ModelImdbTitleResponseDoc {
  "code"?: number;
  "data"?: ModelImdbTitleResponse;
  "msg"?: string;
}

export interface ModelImdbTitleResponse {
  "cast"?: Array<ModelImdbPerson>;
  "content_rating"?: string;
  "directors"?: Array<ModelImdbPerson>;
  "fetched_at"?: string;
  "genres"?: Array<string>;
  "id"?: string;
  "image_url"?: string;
  "plot"?: string;
  "popularity_rank"?: number;
  "public_page_derived"?: boolean;
  "rating_count"?: number;
  "rating_value"?: number;
  "release_date"?: string;
  "runtime_minutes"?: number;
  "source_url"?: string;
  "title"?: string;
  "title_type"?: string;
  "url"?: string;
  "year"?: string;
}

export interface ModelImdbSearchTitleResponseDoc {
  "code"?: number;
  "data"?: ModelImdbSearchTitleResponse;
  "msg"?: string;
}

export interface ModelImdbSearchTitleResponse {
  "fetched_at"?: string;
  "has_more"?: boolean;
  "limit"?: number;
  "results"?: Array<ModelImdbSearchTitleItem>;
  "source_url"?: string;
  "total"?: number;
}

export interface ModelImdbSearchTitleItem {
  "certificate"?: string;
  "genres"?: Array<string>;
  "id"?: string;
  "image_url"?: string;
  "metascore"?: number;
  "plot"?: string;
  "rating_count"?: number;
  "rating_value"?: number;
  "release_date"?: string;
  "runtime_minutes"?: number;
  "title"?: string;
  "title_type"?: string;
  "url"?: string;
  "year"?: number;
}

export interface ModelImdbSearchResponseDoc {
  "code"?: number;
  "data"?: ModelImdbSearchResponse;
  "msg"?: string;
}

export interface ModelImdbSearchResponse {
  "fetched_at"?: string;
  "limit"?: number;
  "query"?: string;
  "results"?: Array<ModelImdbSearchItem>;
  "source_url"?: string;
}

export interface ModelImdbSearchItem {
  "description"?: string;
  "id"?: string;
  "image_url"?: string;
  "title"?: string;
  "title_type"?: string;
  "url"?: string;
  "year"?: string;
}

export interface ModelImdbNameVideosResponseDoc {
  "code"?: number;
  "data"?: ModelImdbNameVideosResponse;
  "msg"?: string;
}

export interface ModelImdbNameVideosResponse {
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "limit"?: number;
  "name"?: string;
  "source_url"?: string;
  "total"?: number;
  "url"?: string;
  "videos"?: Array<ModelImdbVideoItem>;
}

export interface ModelImdbNameImagesResponseDoc {
  "code"?: number;
  "data"?: ModelImdbNameImagesResponse;
  "msg"?: string;
}

export interface ModelImdbNameImagesResponse {
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "images"?: Array<ModelImdbImageItem>;
  "limit"?: number;
  "name"?: string;
  "source_url"?: string;
  "total"?: number;
  "type_counts"?: Array<ModelImdbImageTypeCount>;
  "types"?: Array<string>;
  "url"?: string;
}

export interface ModelImdbNameCreditsResponseDoc {
  "code"?: number;
  "data"?: ModelImdbNameCreditsResponse;
  "msg"?: string;
}

export interface ModelImdbNameCreditsResponse {
  "fetched_at"?: string;
  "id"?: string;
  "public_page_derived"?: boolean;
  "sections"?: Array<ModelImdbNameCreditSection>;
  "source_url"?: string;
  "url"?: string;
}

export interface ModelImdbNameCreditSection {
  "credits"?: Array<ModelImdbNameCreditItem>;
  "has_more"?: boolean;
  "name"?: string;
  "slug"?: string;
  "total"?: number;
}

export interface ModelImdbNameCreditItem {
  "episodes"?: string;
  "id"?: string;
  "role"?: string;
  "title"?: string;
  "url"?: string;
  "year"?: string;
}

export interface ModelImdbNameAwardsResponseDoc {
  "code"?: number;
  "data"?: ModelImdbNameAwardsResponse;
  "msg"?: string;
}

export interface ModelImdbNameAwardsResponse {
  "awards"?: Array<ModelImdbAwardItem>;
  "fetched_at"?: string;
  "has_more"?: boolean;
  "id"?: string;
  "public_page_derived"?: boolean;
  "source_url"?: string;
  "total"?: number;
  "url"?: string;
}

export interface ModelImdbNameResponseDoc {
  "code"?: number;
  "data"?: ModelImdbNameResponse;
  "msg"?: string;
}

export interface ModelImdbNameResponse {
  "bio"?: string;
  "birth_date"?: string;
  "birth_place"?: string;
  "death_date"?: string;
  "fetched_at"?: string;
  "id"?: string;
  "image_url"?: string;
  "known_for"?: Array<ModelImdbNameKnownForItem>;
  "name"?: string;
  "professions"?: Array<string>;
  "public_page_derived"?: boolean;
  "source_url"?: string;
  "url"?: string;
}

export interface ModelImdbNameKnownForItem {
  "category"?: string;
  "id"?: string;
  "title"?: string;
  "url"?: string;
  "year"?: string;
}

export interface ModelImdbImageTypesResponseDoc {
  "code"?: number;
  "data"?: ModelImdbImageTypesResponse;
  "msg"?: string;
}

export interface ModelImdbImageTypesResponse {
  "fetched_at"?: string;
  "total"?: number;
  "types"?: Array<ModelImdbImageType>;
}

export interface ModelImdbImageType {
  "description"?: string;
  "label"?: string;
  "type"?: string;
}

export interface ModelImdbChartsResponseDoc {
  "code"?: number;
  "data"?: ModelImdbChartResponse;
  "msg"?: string;
}

export interface ModelImdbChartResponse {
  "chart"?: string;
  "fetched_at"?: string;
  "limit"?: number;
  "source_url"?: string;
  "titles"?: Array<ModelImdbChartTitle>;
}

export interface ModelImdbChartTitle {
  "cast"?: Array<ModelImdbPerson>;
  "directors"?: Array<ModelImdbPerson>;
  "id"?: string;
  "rank"?: number;
  "rating_count"?: number;
  "rating_value"?: number;
  "title"?: string;
  "url"?: string;
  "writers"?: Array<ModelImdbPerson>;
  "year"?: number;
}

export type ImdbChartsResponse = CrawloraResponse<ModelImdbChartsResponseDoc>;
export interface ImdbChartsParams {
  "chart"?: "top_rated_movies" | "top_rated_tv_shows" | "most_popular_movies" | "most_popular_tv_shows" | "top_rated_english_movies" | "lowest_rated_movies";
  "limit"?: number;
}

export type ImdbImageTypesResponse = CrawloraResponse<ModelImdbImageTypesResponseDoc>;
export interface ImdbImageTypesParams {
}

export type ImdbNameResponse = CrawloraResponse<ModelImdbNameResponseDoc>;
export interface ImdbNameParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbNameAwardsResponse = CrawloraResponse<ModelImdbNameAwardsResponseDoc>;
export interface ImdbNameAwardsParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbNameCreditsResponse = CrawloraResponse<ModelImdbNameCreditsResponseDoc>;
export interface ImdbNameCreditsParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbNameImagesResponse = CrawloraResponse<ModelImdbNameImagesResponseDoc>;
export interface ImdbNameImagesParams {
  "id"?: string;
  "url"?: string;
  "type"?: "behind_the_scenes" | "event" | "poster" | "product" | "production_art" | "publicity" | "still_frame" | "unknown";
  "limit"?: number;
}

export type ImdbNameVideosResponse = CrawloraResponse<ModelImdbNameVideosResponseDoc>;
export interface ImdbNameVideosParams {
  "id"?: string;
  "url"?: string;
  "limit"?: number;
}

export type ImdbSearchResponse = CrawloraResponse<ModelImdbSearchResponseDoc>;
export interface ImdbSearchParams {
  "query": string;
  "limit"?: number;
}

export type ImdbSearchTitleResponse = CrawloraResponse<ModelImdbSearchTitleResponseDoc>;
export interface ImdbSearchTitleParams {
  "title"?: string;
  "title_type"?: string;
  "genres"?: string;
  "release_date_from"?: string;
  "release_date_to"?: string;
  "min_user_rating"?: number;
  "max_user_rating"?: number;
  "min_votes"?: number;
  "max_votes"?: number;
  "min_popularity"?: number;
  "max_popularity"?: number;
  "min_runtime"?: number;
  "max_runtime"?: number;
  "groups"?: string;
  "keywords"?: string;
  "companies"?: string;
  "certificates"?: string;
  "colors"?: string;
  "countries"?: string;
  "languages"?: string;
  "sound_mixes"?: string;
  "role"?: string;
  "characters"?: string;
  "plot"?: string;
  "include_adult"?: boolean;
  "sort"?: string;
  "sort_order"?: string;
  "limit"?: number;
}

export type ImdbTitleResponse = CrawloraResponse<ModelImdbTitleResponseDoc>;
export interface ImdbTitleParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleAwardsResponse = CrawloraResponse<ModelImdbTitleAwardsResponseDoc>;
export interface ImdbTitleAwardsParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleBoxOfficeResponse = CrawloraResponse<ModelImdbTitleBoxOfficeResponseDoc>;
export interface ImdbTitleBoxOfficeParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleCompanyCreditsResponse = CrawloraResponse<ModelImdbTitlePublicFactsResponseDoc>;
export interface ImdbTitleCompanyCreditsParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleConnectionsResponse = CrawloraResponse<ModelImdbTitleConnectionsResponseDoc>;
export interface ImdbTitleConnectionsParams {
  "id"?: string;
  "url"?: string;
  "limit"?: number;
}

export type ImdbTitleCreditsResponse = CrawloraResponse<ModelImdbCreditsResponseDoc>;
export interface ImdbTitleCreditsParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleEpisodesResponse = CrawloraResponse<ModelImdbEpisodesResponseDoc>;
export interface ImdbTitleEpisodesParams {
  "id"?: string;
  "url"?: string;
  "season"?: number;
  "limit"?: number;
}

export type ImdbTitleFilmingLocationsResponse = CrawloraResponse<ModelImdbTitlePublicFactsResponseDoc>;
export interface ImdbTitleFilmingLocationsParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleGoofsResponse = CrawloraResponse<ModelImdbTitlePublicFactsResponseDoc>;
export interface ImdbTitleGoofsParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleImagesResponse = CrawloraResponse<ModelImdbTitleImagesResponseDoc>;
export interface ImdbTitleImagesParams {
  "id"?: string;
  "url"?: string;
  "type"?: "behind_the_scenes" | "event" | "poster" | "product" | "production_art" | "publicity" | "still_frame" | "unknown";
  "limit"?: number;
}

export type ImdbTitleKeywordsResponse = CrawloraResponse<ModelImdbTitlePublicFactsResponseDoc>;
export interface ImdbTitleKeywordsParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleParentalGuideResponse = CrawloraResponse<ModelImdbParentalGuideResponseDoc>;
export interface ImdbTitleParentalGuideParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitlePublicFactsAnalysisResponse = CrawloraResponse<ModelImdbTitlePublicFactsAnalysisResponseDoc>;
export interface ImdbTitlePublicFactsAnalysisParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleQuotesResponse = CrawloraResponse<ModelImdbTitlePublicFactsResponseDoc>;
export interface ImdbTitleQuotesParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleRatingsResponse = CrawloraResponse<ModelImdbRatingsResponseDoc>;
export interface ImdbTitleRatingsParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleReleaseInfoResponse = CrawloraResponse<ModelImdbReleaseInfoResponseDoc>;
export interface ImdbTitleReleaseInfoParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleReviewsResponse = CrawloraResponse<ModelImdbReviewsResponseDoc>;
export interface ImdbTitleReviewsParams {
  "id"?: string;
  "url"?: string;
  "limit"?: number;
}

export type ImdbTitleSimilarResponse = CrawloraResponse<ModelImdbSimilarResponseDoc>;
export interface ImdbTitleSimilarParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleTechnicalSpecsResponse = CrawloraResponse<ModelImdbTechnicalSpecsResponseDoc>;
export interface ImdbTitleTechnicalSpecsParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleTriviaResponse = CrawloraResponse<ModelImdbTitlePublicFactsResponseDoc>;
export interface ImdbTitleTriviaParams {
  "id"?: string;
  "url"?: string;
}

export type ImdbTitleVideosResponse = CrawloraResponse<ModelImdbTitleVideosResponseDoc>;
export interface ImdbTitleVideosParams {
  "id"?: string;
  "url"?: string;
  "limit"?: number;
}

export interface ImdbService {
  charts<T = ImdbChartsResponse>(params?: ImdbChartsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  imageTypes<T = ImdbImageTypesResponse>(params?: ImdbImageTypesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  name<T = ImdbNameResponse>(params?: ImdbNameParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  nameAwards<T = ImdbNameAwardsResponse>(params?: ImdbNameAwardsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  nameCredits<T = ImdbNameCreditsResponse>(params?: ImdbNameCreditsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  nameImages<T = ImdbNameImagesResponse>(params?: ImdbNameImagesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  nameVideos<T = ImdbNameVideosResponse>(params?: ImdbNameVideosParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = ImdbSearchResponse>(params: ImdbSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  searchTitle<T = ImdbSearchTitleResponse>(params?: ImdbSearchTitleParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  title<T = ImdbTitleResponse>(params?: ImdbTitleParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleAwards<T = ImdbTitleAwardsResponse>(params?: ImdbTitleAwardsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleBoxOffice<T = ImdbTitleBoxOfficeResponse>(params?: ImdbTitleBoxOfficeParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleCompanyCredits<T = ImdbTitleCompanyCreditsResponse>(params?: ImdbTitleCompanyCreditsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleConnections<T = ImdbTitleConnectionsResponse>(params?: ImdbTitleConnectionsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleCredits<T = ImdbTitleCreditsResponse>(params?: ImdbTitleCreditsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleEpisodes<T = ImdbTitleEpisodesResponse>(params?: ImdbTitleEpisodesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleFilmingLocations<T = ImdbTitleFilmingLocationsResponse>(params?: ImdbTitleFilmingLocationsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleGoofs<T = ImdbTitleGoofsResponse>(params?: ImdbTitleGoofsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleImages<T = ImdbTitleImagesResponse>(params?: ImdbTitleImagesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleKeywords<T = ImdbTitleKeywordsResponse>(params?: ImdbTitleKeywordsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleParentalGuide<T = ImdbTitleParentalGuideResponse>(params?: ImdbTitleParentalGuideParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titlePublicFactsAnalysis<T = ImdbTitlePublicFactsAnalysisResponse>(params?: ImdbTitlePublicFactsAnalysisParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleQuotes<T = ImdbTitleQuotesResponse>(params?: ImdbTitleQuotesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleRatings<T = ImdbTitleRatingsResponse>(params?: ImdbTitleRatingsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleReleaseInfo<T = ImdbTitleReleaseInfoResponse>(params?: ImdbTitleReleaseInfoParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleReviews<T = ImdbTitleReviewsResponse>(params?: ImdbTitleReviewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleSimilar<T = ImdbTitleSimilarResponse>(params?: ImdbTitleSimilarParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleTechnicalSpecs<T = ImdbTitleTechnicalSpecsResponse>(params?: ImdbTitleTechnicalSpecsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleTrivia<T = ImdbTitleTriviaResponse>(params?: ImdbTitleTriviaParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  titleVideos<T = ImdbTitleVideosResponse>(params?: ImdbTitleVideosParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  imdb: ImdbService;
}

export interface OperationParamsMap {
  "imdb-charts": ImdbChartsParams;
  "imdb-image-types": ImdbImageTypesParams;
  "imdb-name": ImdbNameParams;
  "imdb-name-awards": ImdbNameAwardsParams;
  "imdb-name-credits": ImdbNameCreditsParams;
  "imdb-name-images": ImdbNameImagesParams;
  "imdb-name-videos": ImdbNameVideosParams;
  "imdb-search": ImdbSearchParams;
  "imdb-search-title": ImdbSearchTitleParams;
  "imdb-title": ImdbTitleParams;
  "imdb-title-awards": ImdbTitleAwardsParams;
  "imdb-title-box-office": ImdbTitleBoxOfficeParams;
  "imdb-title-company-credits": ImdbTitleCompanyCreditsParams;
  "imdb-title-connections": ImdbTitleConnectionsParams;
  "imdb-title-credits": ImdbTitleCreditsParams;
  "imdb-title-episodes": ImdbTitleEpisodesParams;
  "imdb-title-filming-locations": ImdbTitleFilmingLocationsParams;
  "imdb-title-goofs": ImdbTitleGoofsParams;
  "imdb-title-images": ImdbTitleImagesParams;
  "imdb-title-keywords": ImdbTitleKeywordsParams;
  "imdb-title-parental-guide": ImdbTitleParentalGuideParams;
  "imdb-title-public-facts-analysis": ImdbTitlePublicFactsAnalysisParams;
  "imdb-title-quotes": ImdbTitleQuotesParams;
  "imdb-title-ratings": ImdbTitleRatingsParams;
  "imdb-title-release-info": ImdbTitleReleaseInfoParams;
  "imdb-title-reviews": ImdbTitleReviewsParams;
  "imdb-title-similar": ImdbTitleSimilarParams;
  "imdb-title-technical-specs": ImdbTitleTechnicalSpecsParams;
  "imdb-title-trivia": ImdbTitleTriviaParams;
  "imdb-title-videos": ImdbTitleVideosParams;
}

export interface OperationResponseMap {
  "imdb-charts": ImdbChartsResponse;
  "imdb-image-types": ImdbImageTypesResponse;
  "imdb-name": ImdbNameResponse;
  "imdb-name-awards": ImdbNameAwardsResponse;
  "imdb-name-credits": ImdbNameCreditsResponse;
  "imdb-name-images": ImdbNameImagesResponse;
  "imdb-name-videos": ImdbNameVideosResponse;
  "imdb-search": ImdbSearchResponse;
  "imdb-search-title": ImdbSearchTitleResponse;
  "imdb-title": ImdbTitleResponse;
  "imdb-title-awards": ImdbTitleAwardsResponse;
  "imdb-title-box-office": ImdbTitleBoxOfficeResponse;
  "imdb-title-company-credits": ImdbTitleCompanyCreditsResponse;
  "imdb-title-connections": ImdbTitleConnectionsResponse;
  "imdb-title-credits": ImdbTitleCreditsResponse;
  "imdb-title-episodes": ImdbTitleEpisodesResponse;
  "imdb-title-filming-locations": ImdbTitleFilmingLocationsResponse;
  "imdb-title-goofs": ImdbTitleGoofsResponse;
  "imdb-title-images": ImdbTitleImagesResponse;
  "imdb-title-keywords": ImdbTitleKeywordsResponse;
  "imdb-title-parental-guide": ImdbTitleParentalGuideResponse;
  "imdb-title-public-facts-analysis": ImdbTitlePublicFactsAnalysisResponse;
  "imdb-title-quotes": ImdbTitleQuotesResponse;
  "imdb-title-ratings": ImdbTitleRatingsResponse;
  "imdb-title-release-info": ImdbTitleReleaseInfoResponse;
  "imdb-title-reviews": ImdbTitleReviewsResponse;
  "imdb-title-similar": ImdbTitleSimilarResponse;
  "imdb-title-technical-specs": ImdbTitleTechnicalSpecsResponse;
  "imdb-title-trivia": ImdbTitleTriviaResponse;
  "imdb-title-videos": ImdbTitleVideosResponse;
}

export interface OperationRequiredParamsMap {
  "imdb-charts": false;
  "imdb-image-types": false;
  "imdb-name": false;
  "imdb-name-awards": false;
  "imdb-name-credits": false;
  "imdb-name-images": false;
  "imdb-name-videos": false;
  "imdb-search": true;
  "imdb-search-title": false;
  "imdb-title": false;
  "imdb-title-awards": false;
  "imdb-title-box-office": false;
  "imdb-title-company-credits": false;
  "imdb-title-connections": false;
  "imdb-title-credits": false;
  "imdb-title-episodes": false;
  "imdb-title-filming-locations": false;
  "imdb-title-goofs": false;
  "imdb-title-images": false;
  "imdb-title-keywords": false;
  "imdb-title-parental-guide": false;
  "imdb-title-public-facts-analysis": false;
  "imdb-title-quotes": false;
  "imdb-title-ratings": false;
  "imdb-title-release-info": false;
  "imdb-title-reviews": false;
  "imdb-title-similar": false;
  "imdb-title-technical-specs": false;
  "imdb-title-trivia": false;
  "imdb-title-videos": false;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "imdb-charts"
  | "imdb-image-types"
  | "imdb-name"
  | "imdb-name-awards"
  | "imdb-name-credits"
  | "imdb-name-images"
  | "imdb-name-videos"
  | "imdb-search"
  | "imdb-search-title"
  | "imdb-title"
  | "imdb-title-awards"
  | "imdb-title-box-office"
  | "imdb-title-company-credits"
  | "imdb-title-connections"
  | "imdb-title-credits"
  | "imdb-title-episodes"
  | "imdb-title-filming-locations"
  | "imdb-title-goofs"
  | "imdb-title-images"
  | "imdb-title-keywords"
  | "imdb-title-parental-guide"
  | "imdb-title-public-facts-analysis"
  | "imdb-title-quotes"
  | "imdb-title-ratings"
  | "imdb-title-release-info"
  | "imdb-title-reviews"
  | "imdb-title-similar"
  | "imdb-title-technical-specs"
  | "imdb-title-trivia"
  | "imdb-title-videos";

export declare const OperationIds: Readonly<{
  ImdbCharts: "imdb-charts";
  ImdbImageTypes: "imdb-image-types";
  ImdbName: "imdb-name";
  ImdbNameAwards: "imdb-name-awards";
  ImdbNameCredits: "imdb-name-credits";
  ImdbNameImages: "imdb-name-images";
  ImdbNameVideos: "imdb-name-videos";
  ImdbSearch: "imdb-search";
  ImdbSearchTitle: "imdb-search-title";
  ImdbTitle: "imdb-title";
  ImdbTitleAwards: "imdb-title-awards";
  ImdbTitleBoxOffice: "imdb-title-box-office";
  ImdbTitleCompanyCredits: "imdb-title-company-credits";
  ImdbTitleConnections: "imdb-title-connections";
  ImdbTitleCredits: "imdb-title-credits";
  ImdbTitleEpisodes: "imdb-title-episodes";
  ImdbTitleFilmingLocations: "imdb-title-filming-locations";
  ImdbTitleGoofs: "imdb-title-goofs";
  ImdbTitleImages: "imdb-title-images";
  ImdbTitleKeywords: "imdb-title-keywords";
  ImdbTitleParentalGuide: "imdb-title-parental-guide";
  ImdbTitlePublicFactsAnalysis: "imdb-title-public-facts-analysis";
  ImdbTitleQuotes: "imdb-title-quotes";
  ImdbTitleRatings: "imdb-title-ratings";
  ImdbTitleReleaseInfo: "imdb-title-release-info";
  ImdbTitleReviews: "imdb-title-reviews";
  ImdbTitleSimilar: "imdb-title-similar";
  ImdbTitleTechnicalSpecs: "imdb-title-technical-specs";
  ImdbTitleTrivia: "imdb-title-trivia";
  ImdbTitleVideos: "imdb-title-videos";
}>;
